### ISSUE TITLE
Constraints of 'elm-community/lazy-list' are probably letting too much stuff through?

### ISSUE THREAD

**Issue by Kr-K** [elm-community/lazy-list#11]
Hello,
currently I am working with fuzz tests for a study project.
In order to get my custom fuzzer (with generator and shrinker) working I added "elm-community/shrink" as a dependency. When I try to run my tests I get an error, which obviously appears because "elm-community/shrink" has a dependency on "elm-community/lazy-list" and there has to be a problem with this dependency.
The error message is:

"Detected errors in 1 module. 
Problem in dependency elm-community/lazy-list 1.0.0 The elm-package.json constraints of 'elm-community/lazy-list' are probably letting too much stuff through. Definitely open an issue on the relevant github repo to get this fixed and save other people from this pain. 
In the meantime, take a look through the direct dependencies of the broken package and see if any of them have had releases recently. If you find the new thing that is causing problems, you can artificially constrain things by adding some extra constraints to your elm-package.json as a stopgap measure."

Can you please tell me if and how it is possible to solve this problem?

Regards
Kelin

**Comment by zwilias** [comment]
The current elm-community/elm-test doesn't doesn't have a dependency om this package, but rather on a set of similarly named [packages](https://github.com/elm-community/elm-test/blob/4.2.0/elm-package.json#L16-L22) maintained by eeue56. The documentation still (mistakenly) link to this and related packages.

Since the API's should be the same, can you try changing your elm-package.json to link to the eeue56 versions, and see if that resolves your issues?

**Comment by Kr-K** [comment]
Thank you! Using "eeue56/elm-lazy-list" and "eeue56/elm-shrink" resolved the issue.
Should I open an issue in the elm-community/elm-test repo to fix the documentation?

**Comment by zwilias** [comment]
https://github.com/elm-community/elm-test/pull/222 It was reported and fixed already, just not released yet. Good reflex, though! ❤️

**Comment by Kr-K** [comment]
Oh, I didn't see that. Thanks :)
